blank_issues_enabled: false
contact_links:
  - name: Dynamo Issues
    url: https://github.com/DynamoDS/Dynamo/issues/new
    about: Report a bug with Dynamo
  - name: Dynamo Revit Issues
    url: https://github.com/DynamoDS/DynamoRevit/issues/new
    about: Report a bug with DynamoRevit
  - name: Dynamo Forum
    url: https://forum.dynamobim.com/
    about: Discussions? Questions? Ideas? Something to share?
