name: Issues workflow
# DynamoWishlist project https://github.com/orgs/DynamoDS/projects/3
# Built-in workflow https://github.com/orgs/DynamoDS/projects/3/workflows/11388102

# The built in workflow
#   - automatically adds any new issues to the project
#   - sets status as 'Triage' when an item is added to the project
#   - sets status as 'Backlog' when an item is reopened
#   - sets status as 'Done' when an item is closed

# This workflow complements the built in workflow and
#   - moves labeled issues labeled to 'Backlog' column the project
#   - moves issues labeled as 'tracked' to 'Todo' column the project

on:
  issues:
    types:
      - labeled

env:
  gh_token: ${{ secrets.DYNAMO_WISHLIST_PROJECT_TOKEN }}
  gh_organization: DynamoDS
  project_id: 3

jobs:
  issue_labeled:
    name: issue labeled
    runs-on: ubuntu-latest
    if: github.event_name == 'issues' && github.event.action == 'labeled'
    steps:
      - name: Move issue to Backlog
        uses: leonsteinhaeuser/project-beta-automations@v2.0.0
        with:
          gh_token: ${{ env.gh_token }}
          organization: ${{ env.gh_organization }}
          project_id: ${{ env.project_id }}
          resource_node_id: ${{ github.event.issue.node_id }}
          status_value: Backlog
      - name: Move issue to Todo
        if: github.event.label.name == 'Tracked'
        uses: leonsteinhaeuser/project-beta-automations@v2.1.0
        with:
          gh_token: ${{ env.gh_token }}
          organization: ${{ env.gh_organization }}
          project_id: ${{ env.project_id }}
          resource_node_id: ${{ github.event.issue.node_id }}
          status_value: Todo
